### ISSUE TITLE
[CHORE] Set expiry time to `useAutoConnect()`

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#280]
## Issue Overview

Currently `useAutoConnect()` will try to reconnect you indefinitely until you log out yourself. We would prefer to have some expiry time to ensure security in the web app.

## Proposed Solutions or Ideas

- Find a way to store last intentional connection time (connection via clicking the connect button, not auto connect).
- Extract wanted TTL duration  to `scaffold.config.ts` in milliseconds.
- Implement `useAutoConnect()` in such a way that it does not allow reconnecting after the TTL has ended. Note please do not implement it in a way that it disconnects a reconnected wallet since it's bad UX

**Comment by Iwueseiter** [comment]
Hi @metalboyrick can I work on this?

**Comment by ShantelPeters** [comment]
@metalboyrick please can I be assigned to this issue ?

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
 

I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, Solidity and rust. My journey with OnlyDust hackathons began at Edition 1, and I've since made 69 contributions across 14 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure. 

I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges. 

As we surf through Edition 8, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will implement an expiry time for the `useAutoConnect` function to enhance security by preventing indefinite reconnections. The steps involved are: 

- **I will analyze the current implementation** of `useAutoConnect` to identify where the connection logic is handled and how reconnections are managed. 

  

- **I will define a TTL (Time to Live) duration** and extract it into the `scaffold.config.ts` file for easy configuration. This will allow for flexibility in setting the expiry time. 

  

- **I will modify the `useAutoConnect` logic** to include a check for the last intentional connection time. This will involve: 

  - Storing the timestamp of the last manual connection (triggered by the user). 

  - Comparing the current time with the stored timestamp against the TTL to determine if reconnection should occur. 

  

- **I will ensure that the implementation does not forcibly disconnect the user’s wallet** upon reaching the TTL, preserving a good user experience. 

  

- **I will test the new functionality** thoroughly to confirm that it behaves as expected, including edge cases where the TTL is exceeded.

**Comment by devcollinss** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
By following these steps, you will effectively implement an expiry time in `useAutoConnect()`, enhancing both security and usability.

### How I plan on tackling this issue
To implement an ### Steps to Implement Expiry Time in `useAutoConnect()`

1. **Store Last Connection Time**:
   - Modify the `useAutoConnect()` hook to store the last intentional connection time. This should be set whenever the user connects via the connect button.

2. **Extract TTL Duration**:
   - Add a configuration entry in `scaffold.config.ts` for the desired TTL duration (in milliseconds).


3. **Implement Expiry Logic**:
   - In the `useAutoConnect()` hook, check if the current time exceeds the last connection time plus the TTL duration before attempting to reconnect.
   

4. **User Experience Consideration**:
   - Ensure that the auto-connect does not forcibly disconnect a wallet if the TTL has expired; instead, gracefully handle the expiration by allowing users to reconnect manually.

5. **Testing**:
   - Test the functionality to ensure that the expiry logic works correctly, allowing reconnections within the TTL but not after.

6. **Documentation**:
   - Update any relevant documentation to reflect the changes in the `useAutoConnect()` behavior and configuration settings.

### Benefits
- **Improved Security**: Adding a TTL enhances security by preventing indefinite connections.
- **User-Friendly**: Maintaining a non-disruptive user experience ensures users can still reconnect easily.

**Comment by petersdt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
kindly assign me this issue as am a frontend developer with experience using frontend technologies


### How I plan on tackling this issue
I recognize that useAutoConnect() currently attempts to reconnect indefinitely until I manually log out, which raises security concerns.
Implement a Connection Expiry:

I will find a way to store the timestamp of the last intentional connection. This means I’ll track when I click the connect button, differentiating it from auto-connection attempts.
Extract TTL Duration:

I will extract the desired time-to-live (TTL) duration and store it in scaffold.config.ts in milliseconds. This will allow me to easily adjust the expiry time as needed.
Modify useAutoConnect():

I will implement changes to useAutoConnect() so that it checks the current time against the stored last connection time. If the TTL has expired, I will ensure that it does not attempt to reconnect.
I will make sure that my implementation does not disconnect a wallet that has reconnected before the TTL expires, as I understand that this would result in a poor user experience.
Test the Implementation:

After making these changes, I will thoroughly test the functionality to ensure that it behaves as expected, allowing reconnections within the TTL and preventing reconnections once the expiry time has passed.

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I have experience in React development and state management, with experience in building secure and user-friendly web applications

### How I plan on tackling this issue
To tackle the issue, I would:

Store Connection Time:
 Implement a mechanism to store the last intentional connection timestamp when the user clicks the connect button.

Configure TTL:
 Extract the desired TTL duration into scaffold.config.ts in milliseconds for easy configuration.

Modify Logic:
 Update the useAutoConnect() hook to check the current time against the stored connection time. If the TTL has expired, prevent reconnection attempts while ensuring that already connected wallets remain active.

Testing: 
Thoroughly test the implementation to confirm that users experience seamless reconnections within the TTL and proper handling after expiry.

**Comment by metalboyrick** [comment]
all yours @Iwueseiter

**Comment by metalboyrick** [comment]
Hi @Iwueseiter, any updates on this issue?

**Comment by Iwueseiter** [comment]
> Hi @Iwueseiter, any updates on this issue?

Yes I’ve been working on it and  I’d create a PR today.
