### ISSUE TITLE
[CHORE] Reconcile `hooks-example-v3` with `main`

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#286]
## Issue Overview

Need to sync `hooks-example-v3` with the v3 version which is located at `main`.

## Proposed Solutions or Ideas

- Merge or rebase (recommended to merge).
- Resolve any conflicts.

**Comment by Immanuelolivia1** [comment]
Can I be assigned to this @metalboyrick

**Comment by Nadai2010** [comment]
Hello everyone, @Immanuelolivia1 the Issues for the OD Hack will be assigned to each of you at the start, prepare your skills.

**Comment by CollinsC1O** [comment]
hello @metalboyrick can I be assigned on this

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I'm a frontend and also a blockchain developer and I would love to hop on this issue. please assign

**Comment by wugalde19** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hi team,
I’m William from Costa Rica 🇨🇷 and a member of the Dojo Coding community.
I am interested in contributing to this issue and believe my skills and background make me well-suited for the task. I’ve worked over 7 years as a Full-Stack engineer in several technologies (including the ones used on this project Typescript/JS) and I am currently expanding my expertise in Rust, Cairo, and Solidity.
I also was one of the winners (elite) of the Speedrun & Scaffold challenge/competition.

Profiles:
https://app.onlydust.com/u/wugalde19
https://github.com/wugalde19




### How I plan on tackling this issue
The way I’d approach this is first pulling latest changes in main, update dependencies and making sure the project runs locally, after that, I’d move to the hooks-example-v3 branch, and then either rebase or merge. If I get any conflicts, then solve then carefully and in case of not being sure I’d go and check the release changes to see what should be the version of the code I should keep, and even if after doing that is not clear to me, I’d ask in the Telegram group.

I’m interested in learning more about your team and looking forward to contributing to this project.

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
i would love to work on this issue i'm a front end web 3 developer i have contributed previously to this repo in past OD Hack and recenttly i have over 50 ODHAck contribution and would love to continue to contribute to this repo

### How I plan on tackling this issue
I would solve the issue quickly and accurately

**Comment by bitfalt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hii! My name is Daniel, I’m a Computer Science student and web3 developer. I’ve done some contributions, finished a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings and I have participated in multiple Hackathons. I’m also a member of the Dojo Coding community. I was also one of the winners for the Speedrun Stark campaign.

### How I plan on tackling this issue
I would approach the issue in the following way:
- Check the branch of `hooks-example-v3`.
- Start by merging the branch.
- I would then start solving any conflicts that might come up during merging.
- Since it is quite a big merge, it is very likely I'll be asking the maintainers for help and some guidance regarding the merge.

**Comment by gianalarcon** [comment]
All yours @bitfalt!

**Comment by bitfalt** [comment]
Thank you so much! I'll start working on it :D

**Comment by metalboyrick** [comment]
Hi @bitfalt, Any updates on this issue?

**Comment by bitfalt** [comment]
hi @metalboyrick, just created a draft PR. I'm going to make the hooks-example-v3 a bit better to separate the different types of hooks as mentioned by @gianalarcon and @Nadai2010.

Created a draft PR #302 so you can check my progress! 

Thank you so much for the opportunity to contribute.
