### ISSUE TITLE
[FEAT] Add verification contract command

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#288]
## Issue Overview

Add a script yarn verify that verifies contracts to a explorer, either `starkscan` or `voyager`

## Proposed Solutions or Ideas

- You can use latest version of snfoundry
- Ideally use cairo scripts with `sncast_std`. You can start using [sncast verify](https://foundry-rs.github.io/starknet-foundry/starknet/verify.html?highlight=verify%20contract#example) 
- should change `package.json` on source and foundry package.
- expected command: `yarn verify --network sepolia`

**Comment by ShantelPeters** [comment]
I’ll like to work on this @metalboyrick

**Comment by Nadai2010** [comment]
Hello everyone, @ShantelPeters  the Issues for the OD Hack will be assigned to each of you at the start, prepare your skills.

**Comment by Jemiiah** [comment]
when OD hack start I would love to take up this issue @metalboyrick @Nadai2010 @0xquantum3labs @jrcarlos2000

**Comment by MPSxDev** [comment]
Glad to have participated in the Speedrunstark, I would love to take on this issue as I know more or less how everything works. I am immediately available to start working on this when ODHack 8.0 starts. @Nadai2010 @metalboyrick @gianalarcon

**Comment by bitfalt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hii! My name is Daniel, I’m a Computer Science student and web3 developer. I’ve done some contributions, finished a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings and I have participated in multiple Hackathons. I’m also a member of the Dojo Coding community. I was also one of the winners for the Speedrun Stark campaign.

### How I plan on tackling this issue
I would approach this issue in the following way:
- Research about proper usage of sncast verify
- Create a command in `package.json` on both paths to verify contracts
- Research about which explorer to use, probably voyager since it retrieves information faster
- Test the command by trying it and ensuring proper behaviour by checking the smart contract has been verified in the selected explorer (Voyager probably).
- Check the documentation to see if it possible to add an entry about this feature, so devs are aware of it.
- I would ask the maintainers if any questions come up during my implementation

**Comment by gianalarcon** [comment]
All yours @MPSxDev!

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I'm a front-end and a blockchain developer and I will love to work on this issue
