### ISSUE TITLE
[TEST] Add unit tests for `useScaffoldWriteContract` and `useScaffoldWriteContract`

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#291]
## Issue Overview

Unit tests required for the indicated hooks to ease future refactoring and feature validations.

## Proposed Solutions or Ideas (more like tips and reminders)

- We use vitest to run the unit tests, can refer to their documentation for the syntax: https://vitest.dev/, Jest developers shouldn't have too much of a hard time getting used to the syntax.
- Note that hooks testing tools are also now imported via `@testing-library/react`,
- Please refer to `README.md` on how to execute the tests
- Use `it.only()` to isolate tests in case you need to, but do not forget to remove it once you are submitting your PR.
- Mock when necessary. please make sure that the tests *NOT ONLY* works on your device
- If you're not sure of the features of the code unit to test, please refer to the [documentation](https://docs.scaffoldstark.com/hooks/), or free to ask on this issue page or on the Telegram Group

## Code Coverage
*IMPORTANT* - When submitting a PR, please provide a screenshot of the coverage for the specific units you are working on. We would like to achieve >= 70 % code coverage. 

Happy Hacking!

Example: 
<img width="833" alt="image" src="https://github.com/user-attachments/assets/ad6e91ce-03c8-4ce3-b6fc-ccd84cf2fe42">

**Comment by ShantelPeters** [comment]
Hi @metalboyrick i will love to work on this issue. Kindly assign please

**Comment by CollinsC1O** [comment]
Hello @metalboyrick I'm a frontend and also a Blockchain developer. I will love to work on this

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello I'm a frontend and also a blockchain developer and I would love to hop on this issue

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
 

I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, Solidity and rust. My journey with OnlyDust hackathons began at Edition 1, and I've since made 69 contributions across 14 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure. 

I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges. 

As we surf through Edition 8, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue


I will develop unit tests for both `useScaffoldWriteContract` and its related functionality. The steps involved are: 

  

- **I will review the hooks' implementations** to understand their behavior and expected outcomes. 

  

- **I will consult the vitest and @testing-library/react documentation** for testing syntax and methodologies. 

  

- **I will create a test file** specifically for `useScaffoldWriteContract`, adhering to the project's structure. 

  

- **I will write unit tests covering:** 

  - Normal behavior of the hooks. 

  - Edge cases, such as invalid inputs or unexpected states. 

  - Necessary mocks for any dependencies to ensure isolated testing. 

  

- **I will run the tests locally**, ensuring at least 70% code coverage as required. 

  

- **I will document and capture a screenshot** of the coverage report for submission with my PR.

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
i am a frontend developer with experience in developing and testing frontend applications 

### How I plan on tackling this issue
I understand that unit tests are needed for the specified hooks to facilitate future refactoring and validate features.
Set Up the Testing Framework:

I will use Vitest to run the unit tests and refer to the Vitest documentation for guidance on syntax and usage.
Import Required Testing Tools:

I will ensure that I import the necessary hooks testing tools from @testing-library/react to effectively handle the testing of hooks.
Review Testing Instructions:

I will consult the README.md file for detailed instructions on executing the tests, ensuring that I follow the project’s established procedures.
Isolate Tests When Necessary:

If I need to focus on specific tests during development, I will use it.only() for isolation. However, I will remember to remove it before submitting my PR to avoid leaving any isolated tests.
Mock Dependencies When Needed:

I will mock any necessary dependencies or external data to ensure the tests function correctly in various environments, not just on my device.
Seek Clarification If Uncertain:

If I am unsure about any features of the code units that require testing, I will refer to the documentation or reach out for assistance on the issue page or via the Telegram group.


I will ensure that my tests achieve at least 70% code coverage. When I submit my PR, I will include a screenshot of the coverage results as proof that I have met this requirement.

**Comment by No-bodyq** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am a fullstack and blockchain dev with experience in writing test for web applications as well as smart contracts

### How I plan on tackling this issue
I'll start by reviewing the Vitest documentation to familiarize myself with the syntax and best practices for writing unit tests.
Next, I'll identify the specific hooks that need unit tests and compile a list of them.
For each identified hook, I'll write unit tests using Vitest, adhering to its syntax and utilizing @testing-library/react for testing hooks.
I'll follow the instructions in the README.md file to understand how to run the tests.
If I need to isolate specific tests, I'll use it.only() to run those tests individually, but ensure it's removed before submitting the PR.
Where mocking is necessary, I'll implement mocking libraries to avoid dependencies on external factors in the tests.

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I would love to work on this issue I'm a frontend web 3 developer with over 50 + contribution to only dust

### How I plan on tackling this issue
Understand the Problem: Before delving into the code, I would thoroughly review the issue description to grasp the specific requirements for adding unit tests for the useScaffoldWriteContract code.

Use vitest for Unit Testing: As per the project's guidelines, I would familiarize myself with the vitest testing framework by referring to their documentation at vitest.dev. This would provide me with insights into the syntax and methodologies required for running the unit tests.

Import Necessary Testing Tools: After understanding the testing requirements, I'd ensure to import the hooks testing tools from @testing-library/react, which are essential for testing React hooks.

Review Execution Instructions: I would thoroughly review the project's README.md file for detailed instructions on executing the tests. Understanding and following these instructions are crucial for successful implementation of the tests.

Isolate Tests When Needed: If necessary, I would make use of it.only() to isolate specific tests during development. However, it's crucial to remember to remove it before submitting the Pull Request (PR) to maintain the integrity of the test suite.

Mock Dependencies: Whenever necessary, I'd utilize mocking techniques to create isolated test environments. This ensures that the tests are not dependent on external factors and function consistently across different setups.

Understand Code Unit Features: I would ensure that I am clear on the features and functionality of the useScaffoldWriteContract code units that require testing. If there are any uncertainties, I would refer to the documentation or seek clarification through the issue page or relevant communication channels.

Achieve Code Coverage: With a focus on code quality, I would aim to achieve at least 70% code coverage with the unit tests. This is crucial to ensure comprehensive validation of the code's functionality and maintain its reliability.

**Comment by Nadai2010** [comment]
All yours @NueloSE

**Comment by metalboyrick** [comment]
Hi @NueloSE , any updates on this issue?

**Comment by NueloSE** [comment]
> Hi @NueloSE , any updates on this issue?

I was having issue setting up the environment but resolved now.

current challenge is the title of my task `Add unit tests for useScaffoldWriteContract and useScaffoldWriteContract` the `useScaffoldWriteContract` is repeated twice 

am I suppose to just test only useScaffoldWriteContract

**Comment by metalboyrick** [comment]
@NueloSE Sorry for the late reply, i meant `useScaffoldMultiWriteContract` as the other one.

Feel free to find us in the telegram group in case you have any questions (especially urgent ones) since sometimes the notifications don't come through here, thanks!
