### ISSUE TITLE
[TEST] Add unit tests for `useScaffoldEventHistory`

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#293]
## Issue Overview

Unit tests required for the indicated hooks to ease future refactoring and feature validations.

## Proposed Solutions or Ideas (more like tips and reminders)

- We use vitest to run the unit tests, can refer to their documentation for the syntax: https://vitest.dev/, Jest developers shouldn't have too much of a hard time getting used to the syntax.
- Note that hooks testing tools are also now imported via `@testing-library/react`,
- Please refer to `README.md` on how to execute the tests
- Use `it.only()` to isolate tests in case you need to, but do not forget to remove it once you are submitting your PR.
- Mock when necessary. please make sure that the tests *NOT ONLY* works on your device
- If you're not sure of the features of the code unit to test, please refer to the [documentation](https://docs.scaffoldstark.com/hooks/), or free to ask on this issue page or on the Telegram Group

## Code Coverage
*IMPORTANT* - When submitting a PR, please provide a screenshot of the coverage for the specific units you are working on. We would like to achieve >= 70 % code coverage. 

Happy Hacking!

Example: 
<img width="833" alt="image" src="https://github.com/user-attachments/assets/ad6e91ce-03c8-4ce3-b6fc-ccd84cf2fe42">

**Comment by Immanuelolivia1** [comment]
Hello @metalboyrick I'll like to work on this.

**Comment by martinvibes** [comment]
hello @dmirgaleev please can i work on this issue :) and would love to be a contributor

**Comment by PabloVillaplana** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am a Full Stack developer with 6 years of experience in the industry, I am super excited to be able to contribute to Web 3 projects, this to continue paving my way as an Open Source Contributor. I am from Dojo Coding Community

### How I plan on tackling this issue
I would like to contribute to this project, because besides the fact that I have been participating in using it, what better way to learn more than by contributing to the project. Adding these tests would be a great opportunity to continue learning.

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello, i am Dprof-in-tech, an experienced Full Stack Blockchain Developer and  I am excited to contribute my skills to this project in this ODHACK 8. With a strong background in Next.js, TypeScript, JavaScript, React, Node.js, Rust and Cairo, I've honed my technical skills across the blockchain development landscape.
My journey with OnlyDust began at Edition 2, and I've since made 34 contributions across 11 projects. This extensive experience on the platform has allowed me to develop a keen understanding of delivering high-quality solutions under tight deadlines. I bring a unique blend of technical prowess and user-centric design to every project, whether I'm crafting immersive 3D experiences or developing innovative smart contracts.
My track record demonstrates my ability to adapt quickly and contribute effectively to diverse challenges. I'm confident in my capacity to tackle new problems and drive innovation in the blockchain space. As we begin ODHACK 8, I'm eager to leverage my hackathon experience and technical skills to push the boundaries of what's possible in blockchain development.
Below is a link to my OnlyDust public profile.
https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
I will set up the testing environment using vitest:
Since the project uses vitest for unit testing, I will ensure my environment is properly configured to run the tests as per the guidelines provided in the project.
I will refer to the Vitest documentation for specific syntax requirements, especially for developers familiar with Jest.
I will use @testing-library/react to test the hooks:
I will ensure I import the necessary utilities from @testing-library/react for testing hooks like useScaffoldEventHistory. These utilities will help simulate how the hook is used within components and allow for effective testing of its behavior.
I will mock external dependencies where necessary:
If useScaffoldEventHistory relies on external APIs or other dependencies, I will mock those to isolate the unit being tested. I will ensure that the tests are not dependent on live data or network requests.
I will focus on writing meaningful test cases:
The tests will cover the main functionality of the hook, including edge cases and error handling. This will ensure that any refactoring or future changes to the hook won’t break existing features.
I will also use it.only() to isolate tests for debugging if necessary, but I’ll ensure that all such isolation is removed before submitting the PR.
I will ensure cross-device test compatibility:
I’ll ensure the tests can run across different development environments, so they don’t only work on my device.
I will capture and report code coverage:
After completing the tests, I’ll run coverage reports and aim for a code coverage of 70% or higher for this hook.
I’ll provide a screenshot of the code coverage in the pull request to demonstrate the quality of the test coverage for useScaffoldEventHistory.

**Comment by DiegoB1911** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I'm a Full Stack Developer with two years of experience, primarily in Next.js. I'm also an active member of Dojo Coding, where I'm expanding my expertise in Cairo and Web3 technologies. I've written numerous unit tests for hooks using Jest, and after reviewing the Vitest documentation, I feel confident in adapting to it smoothly. I'm enthusiastic about learning, contributing, and becoming a part of this project.

### How I plan on tackling this issue
To solve this issue, I would:

Understand the core functionality: First, I would review the purpose of the useScaffoldEventHistory hook and how it interacts with external dependencies.

Mock dependencies and external hooks: I will mock interactions with useDeployedContractInfo, useTargetNetwork, useProvider, and any other dependencies that need to be mocked.

Test multiple scenarios:

Initial state
Successful event fetching
Error handling

Test configuration options: I will cover different configurations such as fromBlock, filters, and options like blockData, transactionData, and receiptData.

Ensure full coverage and correctness: I will ensure all lines and branches are tested.

Document the tests: Finally, I will document the test cases and their outcomes.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
 

I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, Solidity and rust. My journey with OnlyDust hackathons began at Edition 1, and I've since made 69 contributions across 14 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure. 

I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges. 

As we surf through Edition 8, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will implement unit tests for the `useScaffoldEventHistory` hook to ensure its reliability. The steps are as follows: 

  

- **I will evaluate the hook’s implementation** to identify its features and requirements. 

  

- **I will reference vitest and testing-library documentation** to properly structure the tests. 

  

- **I will create a dedicated test file** for the `useScaffoldEventHistory` hook. 

  

- **I will write tests that include:** 

  - Standard functionality tests. 

  - Tests for edge cases and error scenarios. 

  - Mocking dependencies where applicable. 

  

- **I will run the tests to confirm they pass**, aiming for at least 70% coverage. 

  

- **I will document the coverage results** with a screenshot for my PR submission.

**Comment by gregemax** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Tell us about your background and how it can be leveraged:

I have a strong background in JavaScript and experience with testing frameworks like Vitest. I’ve previously written unit tests for React hooks, focusing on ensuring code quality and functionality. My familiarity with best practices in testing will help me implement comprehensive tests for useScaffoldEvent





### How I plan on tackling this issue
I would first review the useScaffoldEventHistory hook to understand its functionality, then write unit tests using Vitest, covering various scenarios and edge cases. I’d ensure to mock dependencies as needed and achieve at least 70% code coverage, providing a coverage report with the PR."

**Comment by No-bodyq** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am a fullstack and blockchain dev with experience in writing tests for web applications and smart contracts

### How I plan on tackling this issue
I'll start by reviewing the Vitest documentation to familiarize myself with the syntax and best practices for writing unit tests.
Next, I'll identify the specific hooks that need unit tests and compile a list of them.
For each identified hook, I'll write unit tests using Vitest, adhering to its syntax and utilizing @testing-library/react for testing hooks.
I'll follow the instructions in the README.md file to understand how to run the tests.
If I need to isolate specific tests, I'll use it.only() to run those tests individually, but ensure it's removed before submitting the PR.
Where mocking is necessary, I'll implement mocking libraries to avoid dependencies on external factors in the tests.

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript

### How I plan on tackling this issue
i will Identify Hooks to Test
Determine which hooks require testing, focusing on those with complex logic or critical functionality. Write Test Scenarios
Create test scenarios for each hook, covering
Happy paths (expected behavior)
Edge cases (boundary values, errors)
Loading states (if applicable)

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello  I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. 

### How I plan on tackling this issue
I will start by reviewing the Vitest documentation. Then, I will set up the testing environment as outlined in the README.md, including installing @testing-library/react for testing React hooks. I'll proceed by writing unit tests, using it.only() to isolate specific tests for debugging when necessary, and mocking external dependencies to ensure reliable tests. Afterward, I will run the tests across different environments or machines to verify they work universally, not just on my device. Once confirmed, I will remove any it.only() instances and submit the PR

**Comment by Nadai2010** [comment]
All yours @Immanuelolivia1

**Comment by metalboyrick** [comment]
Hi @Immanuelolivia1, any updates on this issue?

**Comment by Immanuelolivia1** [comment]
yes i will make a PR before the end of today

**Comment by iossocket** [comment]
@metalboyrick  Hi, may I take this issue? I have solved it locally, and also found another related bug when parsing felt252  in event data
<img width="1810" alt="image" src="https://github.com/user-attachments/assets/ec93c5aa-1062-4361-a003-2cbad6aa7530">

**Comment by metalboyrick** [comment]
@iossocket all yours dude!
